### ISSUE TITLE
Create UserConfigurations

### ISSUE THREAD

**Issue by frogr** [frogr/hub#27]
Goal
Build the core configuration system that manages app customization settings.
Tasks

 Create config/hub_config.yml with sensible defaults
 Build Hub::Config class with ActiveModel integration
 Add validation for all configuration options
 Implement YAML persistence and caching
 Add helper methods (e.g., app_class_name, css_variables)

Basic Schema:
```
app:
  name: "Hub"
  class_name: "Hub" 
  tagline: "Ship your Rails app faster"
  
products:
  - name: "Pro Plan"
    stripe_price_id: "price_xxx"
    price: 49
    features: ["unlimited_users", "priority_support"]

design:
  primary_color: "#3B82F6"
  secondary_color: "#10B981"
  font_family: "Inter"
```

Acceptance Criteria

- [ ] Hub::Config.current loads configuration from YAML
- [ ] Configuration validates all required fields
- [ ] Changes persist to YAML file
- [ ] Helper methods work correctly (app_class_name, etc.)
- [ ] The entire design system helper should be based around inputs from the UserConfig.
